apiVersion: v1
kind: Service
metadata:
  name: ldap-lb
  labels:
    app: ldap
  namespace: {{ .Release.Namespace }}
spec:
  type: LoadBalancer
  ports:
    - port: 389
      name: ldap
    - port: 636
      name: ldaps
  selector:
    app: ldap
