apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  labels:
    app: keycloak
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: {{ .Values.ports.http }}
    targetPort: 8080
    name: http
  {{- if .Values.tls.enabled }}
  - port: {{ .Values.ports.https }}
    targetPort: 8443
    name: https
  {{- end }}
  {{- if .Values.healthcheck.enabled }}
  - port: {{ .Values.ports.healthcheck }}
    name: healthcheck
  {{- end }}
  type: ClusterIP
  selector:
    app: keycloak
