apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-lb
  labels:
    app: keycloak
  namespace: {{ .Release.Namespace }}
spec:
  allocateLoadBalancerNodePorts: false
  ports:
  - port: {{ .Values.ports.http }}
    name: http
  {{- if .Values.tls.enabled }}
  - port: {{ .Values.ports.https }}
    name: https
  {{- end }}
  {{- if .Values.healthcheck.enabled }}
  - port: {{ .Values.ports.healthcheck }}
    name: healthcheck
  {{- end }}
  type: LoadBalancer
  selector:
    app: keycloak
