---
apiVersion: platform.confluent.io/v1beta1
kind: ControlCenter
metadata:
  name: controlcenter
  namespace: confluent
spec:
  podTemplate:
    # for openshift to use default scc
    podSecurityContext: {}
  tls:
    secretRef: tls-controlcenter
  authorization:
    type: rbac
  replicas: 1
  image:
    application: default-route-openshift-image-registry.apps-crc.testing/confluent/cp-enterprise-control-center-next-gen:2.2.0-1-ubi9.arm64
    init: default-route-openshift-image-registry.apps-crc.testing/confluent/confluent-init-container:3.1.1.arm64
  dataVolumeCapacity: 10Gi
  configOverrides:
    jvm:
      - "-Djavax.net.ssl.trustStore=/mnt/sslcerts/truststore.p12"
      - "-Djavax.net.ssl.trustStorePassword=mystorepassword"
      - "-Dorg.apache.kafka.sasl.oauthbearer.allowed.urls=*"
    server:
      - "confluent.controlcenter.command.topic.replication=1"
      - "confluent.controlcenter.replication.factor=1"
      - "confluent.metrics.reporter.topic.replicas=1"
      - "confluent.metrics.topic.replication=1"
      - "confluent.monitoring.interceptor.topic.replication=1"
      - "confluent.controlcenter.internal.topics.replication=1"
  externalAccess:
    type: route
    route:
      domain: confluentdemo.io
      port: 443
  dependencies:
    kafka:
      bootstrapEndpoint: kafkabroker.confluent.svc.cluster.local:9071
      authentication:
        type: oauth
        jaasConfig:
          secretRef: otxt-controlcenter
        oauthSettings:
          tokenEndpointUri: "https://keycloak.identity.svc.cluster.local/realms/confluentdemo/protocol/openid-connect/token"
      tls:
        enabled: true
    mds:
      endpoint: https://kafkabroker.confluent.svc.cluster.local:8090
      ssoProtocol: oidc
      authentication:
        type: oauth
        oauth:
          secretRef: otxt-controlcenter
          configuration:
            tokenEndpointUri: "https://keycloak.identity.svc.cluster.local/realms/confluentdemo/protocol/openid-connect/token"
      tls:
        enabled: true
      tokenKeyPair:
        secretRef: mds-keypair
    prometheusClient:
      url: https://controlcenter.confluent.svc.cluster.local:9090
      authentication:
        type: mtls
      tls:
        enabled: true
        secretRef: tls-controlcenter
    alertManagerClient:
      url: https://controlcenter.confluent.svc.cluster.local:9093
      authentication:
        type: mtls
      tls:
        enabled: true
        secretRef: tls-controlcenter
    connect:
      - name: connect
        url: https://connect.confluent.svc.cluster.local:8083
        tls:
          enabled: true
    schemaRegistry:
      url: https://schemaregistry.confluent.svc.cluster.local:8081
      tls:
        enabled: true
  services:
    prometheus:
      image: default-route-openshift-image-registry.apps-crc.testing/confluent/cp-enterprise-prometheus:2.2.0-1-ubi9.arm64
      authentication:
        type: mtls
      tls:
        secretRef: tls-controlcenter
      pvc:
        dataVolumeCapacity: 10Gi
    alertmanager:
      image: default-route-openshift-image-registry.apps-crc.testing/confluent/cp-enterprise-alertmanager:2.2.0-1-ubi9.arm64
      authentication:
        type: mtls
      tls:
        secretRef: tls-controlcenter
