apiVersion: v1
name: keycloak
home: https://github.com/huynconfluent/environment-install/idp/keycloak/helm
version: 1.0.0
appVersion: 1.0.0
keywords:
  - idp
  - keycloak
maintainers:
  - name: Huy Nguyen
    email: huy.nguyen@confluent.io
